apiVersion: v1
kind: Service
metadata:
  name: ucloud-nginx-out-tcp-new
  labels:
    app: ucloud-nginx-out-tcp-new
  annotations:
    "service.beta.kubernetes.io/ucloud-load-balancer-vserver-protocol": "HTTPS"       
    "service.beta.kubernetes.io/ucloud-load-balancer-vserver-monitor-type": "Path" 
    "service.beta.kubernetes.io/ucloud-load-balancer-vserver-ssl-cert": "ssl_id"
    "service.beta.kubernetes.io/ucloud-load-balancer-vserver-monitor-path": "/"
    "service.beta.kubernetes.io/ucloud-load-balancer-eip-bandwidth": "10"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
  selector:
    app: ucloud-nginx-out-tcp-new
